export const COLLECTION: string = 'Collection';
export const VIDEOPLAYER: string = 'Video Player';
export const BROWSE: string = 'Browse';
export const COLLECTION_ZOOM: string = 'Collection Zoom';
export const BROWSE_ONLY: string = 'Browse Only';
export const NEWSFEED: string = 'Newsfeed';
export const ZOOM: string = 'Zoom';
export const FILTER: string = 'Filter';
export const VIEW: string = 'VIEW';